#! /usr/bin/env python3

from docker_manager import DockerManagerWidget
from PyQt5.QtWidgets import QApplication
import sys

def main():
    app = QApplication(sys.argv)
    widget = DockerManagerWidget()
    widget.show()
    app.exec()


if __name__ == '__main__':
    main()
